# vim:fileencoding=utf-8:foldmethod=marker

# : Manager {{{

[mgr]
cwd = { fg = "#83a598" }

# Hovered
hovered         = { fg = "#1d2021", bg = "#83a598" }
preview_hovered = { underline = true }

# Find
find_keyword  = { fg = "#8ec07c", italic = true }
find_position = { fg = "#e6bf86", bg = "reset", italic = true }

# Marker
marker_selected = { fg = "#8ec07c", bg = "#8ec07c" }
marker_copied   = { fg = "#8ec07c", bg = "#8ec07c" }
marker_cut      = { fg = "#fb4934", bg = "#fb4934" }

# Tab
tab_active   = { fg = "#1d2021", bg = "#665c54" }
tab_inactive = { fg = "#928374", bg = "#3c3836" }
tab_width    = 1

# Border
border_symbol = "│"
border_style  = { fg = "#665c54" }

# Highlighting
# syntect_theme = "~/.config/yazi/Gruvbox-Dark.tmTheme"

# : }}}


# : Status {{{

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#3c3836", bg = "#3c3836" }

# Mode
mode_normal = { fg = "#ebdbb2", bg = "#665c54", bold = true }
mode_select = { fg = "#1d2021", bg = "#8ec07c", bold = true }
mode_unset  = { fg = "#1d2021", bg = "#e6bf86", bold = true }

# Progress
progress_label  = { fg = "#ebdbb2", bold = true }
progress_normal = { fg = "#83a598", bg = "#3c3836" }
progress_error  = { fg = "#fb4934", bg = "#3c3836" }

# Permissions
permissions_t = { fg = "#665c54" }
permissions_r = { fg = "#8ec07c" }
permissions_w = { fg = "#e6bf86" }
permissions_x = { fg = "#8ec07c" }
permissions_s = { fg = "#665c54" }

# : }}}


# : Input {{{

[input]
border   = { fg = "#665c54" }
title    = {}
value    = {}
selected = { reversed = true }

# : }}}


# : Select {{{

[select]
border   = { fg = "#665c54" }
active   = { fg = "#e6bf86" }
inactive = {}

# : }}}


# : Tasks {{{

[tasks]
border  = { fg = "#665c54" }
title   = {}
hovered = { underline = true }

# : }}}


# : Which {{{

[which]
mask            = { bg = "#3c3836" }
cand            = { fg = "#83a598" }
rest            = { fg = "#928374" }
desc            = { fg = "#e6bf86" }
separator       = "  "
separator_style = { fg = "#665c54" }

# : }}}


# : Help {{{

[help]
on      = { fg = "#e6bf86" }
exec    = { fg = "#83a598" }
desc    = { fg = "#928374" }
hovered = { bg = "#665c54", bold = true }
footer  = { fg = "#3c3836", bg = "#928374" }

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#83a598" },

    # Videos
    { mime = "video/*", fg = "#8ec07c" },
    { mime = "audio/*", fg = "#8ec07c" },

    # Archives
    { mime = "application/zip",             fg = "#e6bf86" },
    { mime = "application/gzip",            fg = "#e6bf86" },
    { mime = "application/x-tar",           fg = "#e6bf86" },
    { mime = "application/x-bzip",          fg = "#e6bf86" },
    { mime = "application/x-bzip2",         fg = "#e6bf86" },
    { mime = "application/x-7z-compressed", fg = "#e6bf86" },
    { mime = "application/x-rar",           fg = "#e6bf86" },

    # Fallback
    { url = "*", fg = "#ebdbb2" },
    { url = "*/", fg = "#83a598" }
]

# : }}}


# : Icons {{{

[icon]

dirs = [
    { name = ".config",     text = "", fg = "#689d6a" },
    { name = ".git",        text = "", fg = "#689d6a" },
    { name = ".github",     text = "", fg = "#689d6a" },
    { name = ".npm",        text = "", fg = "#689d6a" },
    { name = "Desktop",     text = "", fg = "#689d6a" },
    { name = "Development", text = "", fg = "#689d6a" },
    { name = "Documents",   text = "", fg = "#689d6a" },
    { name = "Downloads",   text = "", fg = "#689d6a" },
    { name = "Library",     text = "", fg = "#689d6a" },
    { name = "Movies",      text = "", fg = "#689d6a" },
    { name = "Music",       text = "", fg = "#689d6a" },
    { name = "Pictures",    text = "", fg = "#689d6a" },
    { name = "Public",      text = "", fg = "#689d6a" },
    { name = "Videos",      text = "", fg = "#689d6a" },
]

prepend_conds = [
    { if = "dir & hovered", text = "", fg = "#689d6a" },
    { if = "dir",           text = "", fg = "#689d6a" },
]

# : }}}

