"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 600

format = """
[](color_border_active)\
$os\
$username\
[](bg:color_border fg:color_border_active)\
$directory\
[](fg:color_border bg:color_aqua)\
$git_branch\
$git_status\
[](fg:color_aqua bg:color_teal)\
$c\
$rust\
$golang\
$nodejs\
$lua\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:color_teal bg:color_ochre)\
$docker_context\
[](fg:color_ochre bg:color_border)\
$time\
[ ](fg:color_border)\
$line_break$character"""

palette = 'verdigris'

[palettes.verdigris]
color_fg0 = '#fbf1c7'
color_fg1 = '#ebdbb2'
color_fg_alt = '#d4be9a'
color_muted = '#bdae93'
color_faint = '#928374'
color_bg0 = '#141917'
color_bg1 = '#1d2520'
color_bg2 = '#263128'
color_bg3 = '#344033'
color_bg4 = '#465241'
color_bg5 = '#5b6654'
color_border = '#3c3836'
color_border_hover = '#504945'
color_border_active = '#665c54'
color_fern = '#8ec07c'
color_aqua = '#689d6a'
color_teal = '#458588'
color_blue = '#458588'
color_cyan = '#83a598'
color_moss = '#98971a'
color_olive = '#70764a'
color_olive_muted = '#8c945c'
color_brown_green = '#604b29'
color_ochre = '#e6bf86'
color_ochre_alt = '#d8a65c'
color_dark_ochre = '#8b6021'
color_orange = '#d65d0e'
color_red = '#cc241d'
color_purple = '#b16286'

[os]
disabled = false
style = "bg:color_border_active fg:color_fg0"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇 "
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = false
style_user = "bg:color_border_active fg:color_fg0"
style_root = "bg:color_border_active fg:color_fg0"
format = '[ $user ]($style)'

[directory]
style = "fg:color_fg0 bg:color_border"
format = "[ $path ]($style)"
truncation_length = 1
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol $branch ](fg:color_fg0 bg:color_aqua)]($style)'

[git_status]
style = "bg:color_aqua"
format = '[[($all_status$ahead_behind )](fg:color_fg0 bg:color_aqua)]($style)'

[nodejs]
symbol = ""
style = "bg:color_teal"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_teal)]($style)'

[c]
symbol = " "
style = "bg:color_teal"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_teal)]($style)'

[rust]
symbol = ""
style = "bg:color_teal"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_teal)]($style)'

[golang]
symbol = ""
style = "bg:color_teal"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_teal)]($style)'

[lua]
symbol = " "
style = "bg:color_teal"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_teal)]($style)'

[php]
symbol = ""
style = "bg:color_teal"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_teal)]($style)'

[java]
symbol = " "
style = "bg:color_teal"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_teal)]($style)'

[kotlin]
symbol = ""
style = "bg:color_teal"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_teal)]($style)'

[haskell]
symbol = ""
style = "bg:color_teal"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_teal)]($style)'

# [python]
# symbol = ""
# style = "bg:color_teal"
# format = '[[ ${symbol}${pyenv_prefix}(${version} )](\($virtualenv\) )]($style)]'

[python]
symbol = " "
style = "bg:color_teal fg:color_fg0"
format = '[${symbol}( ${version})( \($virtualenv\))]($style)'

[docker_context]
symbol = ""
style = "bg:color_ochre"
format = '[[ $symbol( $context) ](fg:color_fg0 bg:color_ochre)]($style)'

[time]
disabled = false
time_format = "%l:%M%p"
style = "bg:color_border"
format = '[[  $time ](fg:color_fg0 bg:color_border)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_aqua)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_moss)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_ochre)'
