# Verdigris-dark ncspot theme [ background = "default" to enjoy terminal transparency ]
[theme]
#background = "#1d2021"
background = "default"
primary = "#ebdbb2"
secondary = "#d4be9a"
title = "#e6bf86"
playing = "#83a598"
playing_selected = "#83a598"
playing_bg = "#1d2021"
highlight = "#689d6a"
highlight_bg = "#1d2021"
error = "#fbf1c7"
error_bg = "#cc241d"
statusbar = "#ebdbb2"
statusbar_progress = "#8ec07c"
statusbar_bg = "#3c3836"
cmdline = "#1d2021"
cmdline_bg = "#e6bf86"
search_match = "#e6bf86"
