# Fuzzel application launcher — Verdigris theme.

[main]
font=Noto Sans Mono:size=16
use-bold=yes
line-height=28
dpi-aware=auto
prompt="❯ "
placeholder=Search applications…
icon-theme=Adwaita
icons-enabled=yes
hide-before-typing=no
fields=name,generic,keywords,exec
filter-desktop=yes
match-mode=fzf
sort-result=yes
match-counter=yes
show-actions=no
terminal=ghostty -e {cmd}
anchor=center
lines=16
width=72
horizontal-pad=32
vertical-pad=14
inner-pad=10
image-size-ratio=0.25
layer=overlay
keyboard-focus=exclusive
exit-on-keyboard-focus-loss=yes

[colors]
background=282828f5
text=ebdbb2ff
message=ebdbb2ff
prompt=8ec07cff
placeholder=928374ff
input=ebdbb2ff
match=83a598ff
selection=665c54ff
selection-text=fbf1c7ff
selection-match=e6bf86ff
counter=689d6aff
border=689d6aff

[border]
width=2
radius=12
selection-radius=8

[dmenu]
mode=text
exit-immediately-if-empty=yes
